print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 15
            client:
                timeout-in-seconds: 5

swagger:
    schemes: [https]
    host: ${SWAGGER_HOST:localhost}
    port: "80"
