print-status: False

api:
    server:
        scheme: http
        port: 5042
        host: 0.0.0.0
    security:
        secret: ${SECURITY_KEY:local-secret-key}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False
        # driver: ${DATABASE_DRIVER:}
        # database: ${DATABASE_NAME:}
        # username: ${DATABASE_USERNAME:}
        # password: ${DATABASE_PASSWORD:}
        # host: ${DATABASE_HOST:}
        # port: ${DATABASE_PORT:}
        # schema: ${DATABASE_SCHEMA:}
        # url: ${DATABASE_URL:}

swagger:
    host: localhost:${api.server.port}
