print-status: False
api:
    name: HealthCheckManagerApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    session:
        secret: ${SESSION_SECRET:default}
    api-key:
        secret: ${API_KEY_SECRET:default}
    security:
        secret: ${SECURITY_SECRET:default}
    server:
        scheme: http
        host: 0.0.0.0
        port: 5042
        base-url: /health-check-manager-api
    scheduler:
        time-zone: ${SCHEDULER_TIMEZONE:Brazil/East}
        enable: ${ENABLE_SCHEDULER_API:True}
        mute-logs: False
    listener:
        enable: ${ENABLE_LISTENER_API:True}
    emitter:
        enable: ${ENABLE_EMITER_API:True}

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 2
            client:
                timeout-in-seconds: 5

queue-manager-api:
    base-url: ${QUEUE_MANAGER_API_HOST}/queue-manager-api
    api-key: ${QUEUE_MANAGER_API_API_KEY}
    api-notifications:
        queue-key: ${API_NOTIFICATIONS_QUEUE_KEY}
        emitter:
            timeout: 2

swagger:
    # schemes: [${api.server.scheme}] ###- bug
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
    info:
        title: ${api.name}
        version: 0.0.1
        description: Health Check Manager Api
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
