print-status: False

api:
    server:
        scheme: http
        port: 5042
        host: 0.0.0.0
    security:
        secret: ${SECURITY_KEY:local-secret-key}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    host: localhost:${api.server.port}
