print-status: False
api:
    name: HealthCheckManagerApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    security:
        secret: default
    server:
        scheme: https
        host: 0.0.0.0
        port: 5042
        base-url: /health-check-manager-api
    scheduler:
        enable: ${SCHEDULER_API_ENABLE:True}

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 2
            client:
                timeout-in-seconds: 2

ai-voice-api:
    base-url: http://192.168.25.3:5050/ai-voice-api

swagger:
    host: ${SWAGGER_HOST:}:${api.server.port}
    schemes: [${api.server.scheme}]
    info:
        title: {api.name}
        version: 0.0.1
        description: Health Check Manager Api
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
