print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 1
            client:
                timeout-in-seconds: 3

swagger:
    schemes: [${api.server.scheme}] ###- bug
    host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
