print-status: False

api:
    server:
        scheme: http
        port: 5042
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 10
            client:
                timeout-in-seconds: 10

swagger:
    host: 192.168.25.3:${api.server.port}
