print-status: False

api:
    # server:
    #     scheme: https
    #     host: data.ai-automation-tools.com
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

health-check:
    sheduler:
        health-check:
            interval-in-minutes: 15
            client:
                timeout-in-seconds: 5

swagger:
    schemes: [https]
    host: data.ai-automation-tools.com
    port: "80"
